 -- Item Types Inserts:
INSERT INTO item_types (item_type_name) VALUES ('Fin');
INSERT INTO item_types (item_type_name) VALUES ('Hat');
INSERT INTO item_types (item_type_name) VALUES ('Tail');
INSERT INTO item_types (item_type_name) VALUES ('Effect');

-- Rarity Types Inserts:
INSERT INTO rarity_types (rarity_name) VALUES ('uncommon');
INSERT INTO rarity_types (rarity_name) VALUES ('common');
INSERT INTO rarity_types (rarity_name) VALUES ('epic');
INSERT INTO rarity_types (rarity_name) VALUES ('rare');
INSERT INTO rarity_types (rarity_name) VALUES ('legendary');
INSERT INTO rarity_types (rarity_name) VALUES ('award');

-- Items Inserts:
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Angel_Fin', '00_Angel_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Angel_Hat', '00_Angel_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Angler_Fin', '00_Angler_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Angler_Hat', '00_Angler_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Angler_Tail', '00_Angler_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Ascend_Effect', '00_Ascend_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Balloon_Effect', '00_Balloon_Effect', 4, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Basilisk_Fin', '00_Basilisk_Fin', 1, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Basilisk_Hat', '00_Basilisk_Hat', 2, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Basilisk_Tail', '00_Basilisk_Tail', 3, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bat_Effect', '00_Bat_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bat_Fin', '00_Bat_Fin', 1, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bat_Hat', '00_Bat_Hat', 2, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bee_Fin', '00_Bee_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bee_Hat', '00_Bee_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bee_Tail', '00_Bee_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bluejay_Fin', '00_Bluejay_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bluejay_Hat', '00_Bluejay_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bluejay_Tail', '00_Bluejay_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bling_Effect', '00_Bling_Effect', 4, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bomb_Effect', '00_Bomb_Effect', 4, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bow_Fin', '00_Bow_Fin', 1, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bow_Hat', '00_Bow_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bunny_Hat', '00_Bunny_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Bunny_Tail', '00_Bunny_Tail', 3, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Butterfly_Effect', '00_Butterfly_Effect', 4, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Candy_Effect', '00_Candy_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Cat_Fin', '00_Cat_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Cat_Hat', '00_Cat_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Cat_Tail', '00_Cat_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Chained_Fin', '00_Chained_Fin', 1, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Chained_Hat', '00_Chained_Hat', 2, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Chained_Tail', '00_Chained_Tail', 3, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Chaotic_Effect', '00_Chaotic_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_ChristmasCandy_Effect', '00_ChristmasCandy_Effect', 4, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_ChristmasPresent_Effect', '00_ChristmasPresent_Effect', 4, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_ChristmasSock_Effect', '00_ChristmasSock_Effect', 4, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Cloud_Effect', '00_Cloud_Effect', 4, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_CosmicNova_Effect', '00_CosmicNova_Effect', 4, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Crown_Hat', '00_Crown_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Crystal_Fin', '00_Crystal_Fin', 1, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Crystal_Hat', '00_Crystal_Hat', 2, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Crystal_Tail', '00_Crystal_Tail', 3, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Cyber_Fin', '00_Cyber_Fin', 1, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Cyber_Hat', '00_Cyber_Hat', 2, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Cyber_Tail', '00_Cyber_Tail', 3, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_CyberTech_Effect', '00_CyberTech_Effect', 4, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Devil_Fin', '00_Devil_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Devil_Hat', '00_Devil_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Devil_Tail', '00_Devil_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Dragon_Fin', '00_Dragon_Fin', 1, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Dragon_Hat', '00_Dragon_Hat', 2, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Dragon_Tail', '00_Dragon_Tail', 3, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Dragonfly_Hat', '00_Dragonfly_Hat', 2, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Egg_Hat', '00_Egg_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Emitter_Effect', '00_Emitter_Effect', 4, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Feather_Effect', '00_Feather_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Fire Demon_Hat', '00_Fire Demon_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Fire Demon_Tail', '00_Fire Demon_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Fireworks_Effect', '00_Fireworks_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Flower_Effect', '00_Flower_Effect', 4, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_FlyingFish_Effect', '00_FlyingFish_Effect', 4, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_GemStone_Effect', '00_GemStone_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_GhostAscend_Effect', '00_GhostAscend_Effect', 4, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_GhostFire_Effect', '00_GhostFire_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_GoldRain_Effect', '00_GoldRain_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Heart_Effect', '00_Heart_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_HollowDiamond_Effect', '00_HollowDiamond_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Ink Youkai_Fin', '00_Ink Youkai_Fin', 1, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Ink Youkai_Hat', '00_Ink Youkai_Hat', 2, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Ink Youkai_Tail', '00_Ink Youkai_Tail', 3, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Kitsune_Fin', '00_Kitsune_Fin', 1, 1000, 100, 5, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Kitsune_Hat', '00_Kitsune_Hat', 2, 1000, 100, 5, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Kitsune_Tail', '00_Kitsune_Tail', 3, 1000, 100, 5, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Lantern_Effect', '00_Lantern_Effect', 4, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Leaf_Effect', '00_Leaf_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Lightning_Effect', '00_Lightning_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Math_Effect', '00_Math_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Mermaid_Effect', '00_Mermaid_Effect', 4, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Mermaid_Fin', '00_Mermaid_Fin', 1, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Mermaid_Tail', '00_Mermaid_Tail', 3, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Meteor_Effect', '00_Meteor_Effect', 4, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Miasma_Effect', '00_Miasma_Effect', 4, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Monarch_Fin', '00_Monarch_Fin', 1, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Monarch_Hat', '00_Monarch_Hat', 2, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Monitor_Effect', '00_Monitor_Effect', 4, 1000, 100, 1, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Mouse_Fin', '00_Mouse_Fin', 1, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Mouse_Hat', '00_Mouse_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Mouse_Tail', '00_Mouse_Tail', 3, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_MusicNotes_Effect', '00_MusicNotes_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_MusicWave_Effect', '00_MusicWave_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Narwhal_Fin', '00_Narwhal_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Narwhal_Hat', '00_Narwhal_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Narwhal_Tail', '00_Narwhal_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Outfox_Fin', '00_Outfox_Fin', 1, 1000, 100, 6, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Outfox_Hat', '00_Outfox_Hat', 2, 1000, 100, 6, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Outfox_Tail', '00_Outfox_Tail', 3, 1000, 100, 6, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Ox_Hat', '00_Ox_Hat', 2, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Ox_Tail', '00_Ox_Tail', 3, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Poop_Hat', '00_Poop_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Raven_Fin', '00_Raven_Fin', 1, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Raven_Hat', '00_Raven_Hat', 2, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Raven_Tail', '00_Raven_Tail', 3, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Runes_Effect', '00_Runes_Effect', 4, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Sakura_Effect', '00_Sakura_Effect', 4, 1000, 100, 5, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Scarecrow_Fin', '00_Scarecrow_Fin', 1, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Scarecrow_Hat', '00_Scarecrow_Hat', 2, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Scarecrow_Tail', '00_Scarecrow_Tail', 3, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Shield_Effect', '00_Shield_Effect', 4, 1000, 100, 5, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_ShootingStar_Effect', '00_ShootingStar_Effect', 4, 1000, 100, 4, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_SnowFlakes_Effect', '00_SnowFlakes_Effect', 4, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Sprout One_Hat', '00_Sprout One_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Sprout Two_Hat', '00_Sprout Two_Hat', 2, 1000, 100, 2, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Star_Effect', '00_Star_Effect', 4, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_StellarMoon_Effect', '00_StellarMoon_Effect', 4, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_StoneHenge_Effect', '00_StoneHenge_Effect', 4, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Unicorn_Hat', '00_Unicorn_Hat', 2, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Unicorn_Tail', '00_Unicorn_Tail', 3, 1000, 100, 4, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Whiteout Youkai_Fin', '00_Whiteout Youkai_Fin', 1, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Whiteout Youkai_Hat', '00_Whiteout Youkai_Hat', 2, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Whiteout Youkai_Tail', '00_Whiteout Youkai_Tail', 3, 1000, 100, 3, False);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Witch_Fin', '00_Witch_Fin', 1, 1000, 100, 1, True);
INSERT INTO items (item_name, unity_name, item_type_id, silver_cost, gold_cost, rarity_id, is_general_store_item) VALUES ('00_Witch_Hat', '00_Witch_Hat', 2, 1000, 100, 1, True);